export enum JobStatus {
  APPLIED = 'APPLIED',
  INTERVIEW_SCHEDULED = 'INTERVIEW_SCHEDULED',
  INTERVIEW_COMPLETED = 'INTERVIEW_COMPLETED',
  OFFER_RECEIVED = 'OFFER_RECEIVED',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  WITHDRAWN = 'WITHDRAWN',
  NO_RESPONSE = 'NO_RESPONSE',
}

export enum ResponseStatus {
  NO_RESPONSE = 'NO_RESPONSE',
  POSITIVE = 'POSITIVE',
  NEGATIVE = 'NEGATIVE',
  NEUTRAL = 'NEUTRAL',
}

export enum JobLocationType {
  REMOTE = 'REMOTE',
  ONSITE = 'ONSITE',
  HYBRID = 'HYBRID',
}

export enum AppliedVia {
  LINKEDIN = 'LINKEDIN',
  COMPANY_WEBSITE = 'COMPANY_WEBSITE',
  RECRUITER = 'RECRUITER',
  REFERRAL = 'REFERRAL',
  JOB_BOARD = 'JOB_BOARD',
  OTHER = 'OTHER',
}

export enum InterviewType {
  PHONE = 'PHONE',
  VIDEO = 'VIDEO',
  IN_PERSON = 'IN_PERSON',
  ASSIGNMENT = 'ASSIGNMENT',
  GROUP = 'GROUP',
  PANEL = 'PANEL',
}

export enum JobPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum JobSourceType {
  MANUAL = 'MANUAL',
  IMPORTED = 'IMPORTED',
  API = 'API',
}

export enum FollowUpStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum FollowUpType {
  EMAIL = 'EMAIL',
  PHONE = 'PHONE',
  LINKEDIN = 'LINKEDIN',
  IN_PERSON = 'IN_PERSON',
  OTHER = 'OTHER',
}

export enum JobTimelineEventType {
  APPLIED = 'APPLIED',
  APPLICATION_VIEWED = 'APPLICATION_VIEWED',
  PHONE_SCREEN = 'PHONE_SCREEN',
  INTERVIEW = 'INTERVIEW',
  OFFER = 'OFFER',
  REJECTION = 'REJECTION',
  WITHDRAWAL = 'WITHDRAWAL',
  ACCEPTED = 'ACCEPTED',
  DECLINED = 'DECLINED',
  NOTE_ADDED = 'NOTE_ADDED',
  FOLLOW_UP = 'FOLLOW_UP',
  OTHER = 'OTHER',
}

export enum JobDocumentType {
  RESUME = 'RESUME',
  COVER_LETTER = 'COVER_LETTER',
  PORTFOLIO = 'PORTFOLIO',
  CERTIFICATION = 'CERTIFICATION',
  OTHER = 'OTHER',
}
